### PR TITLE
Array initialization example

### PR DESCRIPTION
**Pull request by Pidroh**
Added an example to array initialization since I felt like the manual was unclear

### CODE REVIEW

**Comment by Simn** [comment]
I'm fine with that, but let's please lose the ` : Array` type-hint because that's not very haxe-idomatic.

**Comment by Pidroh** [comment]
@Simn 
This is what you meant? I'm quite a beginner at Haxe.

**Comment by Simn** [comment]
Yes, but please do it for both lines!

**Comment by Pidroh** [comment]
Oh, that was dumb. Done!

**Comment by Simn** [comment]
Thanks!

The fact that `b` appears before `a` is pretty strange, but I feel rebellious today so I'll merge it anyway.

**Pull request merged**
