### PR TITLE
Using haxelib

### PR DESCRIPTION
**Pull request by markknol**
Describes the possible haxelib commands in an ordered list

### CODE REVIEW

**Comment by Simn** [comment]
Are nested lists looking good now in the markdown output? I remember there being some issues with it.

**Comment by markknol** [comment]
In this [preview editor](http://jbt.github.io/markdown-editor/#fVffi9tGEH73X7GQh96Fs0KgT6EUGkKbPCSEcqWE48BraSxtLO2quyv73L++34x2ZdlyE8hhdmfn5zffjF69Um/fFj+rv4KxtfqoX6g129Xq007FhtSmGQ82qnRdp22lTFD0QuUQqVJHExs3RKXtSWlfDx3ZGB6Uiar3Bj9xAeFGDyGaA6nWhKjcTum2VfqgTau3LZ0fFuq3sqQQxPAvTYz9uzdvYLtgHwrn61/VkbbBRFLRqYOho2hiaUh57Q2Fs95CrVaPuNq5tnVHji1FABlPZ7l3q9Vr9V4HU+KBwr/XU9DK2BDZxFPv3Xcq49rqjp7V04F8MM4+b5ABXGcx9qRGoFYl+UJ9c4MqkQXXRzyA0EmFnkqzQ8LSLxhO+jisLWV1VBXq/UlVtNNDGx9UqyMhf55a0gHJz4/EhYtn12EMfYW3V1Fs8jH8QHbanMQTe4FIjM8WkyEkdKG39rqiTf4xlWNyJSci/L/SxwaIyuCCeNczbnBid8Z3mtOGGnpFumyyIcFNzvG1V546d5iuJdhFxZIMm+n6luIkrmDJ2XZWnVmmze58uDDL4E7aBec/yAVHOiYjaQb0f88hJqkHeZwth8F7N9gKWrYnhTKVe4IiM/ZKiVs0EBynhVuB4g/gGzn54nPZaFvThbpsnLOvr4H9OPOuQ38zAnXrSVenORJfq08W71MdFw0WSHvE/HR0vnqeZ4/9mPJ1bAyEGo2KERiH2B0pKxyrKJTeSHcpWCkb7vRz6VjxIicGLi26QWxzkOqEnjUzr/VWOO4qA4tmCPDrif9mjRLIXBHrSlo+zl5daxLo15uRQyUTHydo9w7859CkvY5Nah4uIZJyFqspzmC3nThk4TMrWSQiUTffSdvOuJXpH1cV9QQs2pIP76DcWNgxdlJcvHTt5h7F/0AHal3P9H6j+MO2M2d0Fv+aHubHU6aAHijXtZB9iqxQaSxJsgUCCH6we+uO9oEL99PIhaAObsGwh1947qlGLRg3qEBZopPipaqMXHqBXBBNE6+OnARF3Ae48HAsBAFW1pHJo3JIiHVx1KNOFGUYZk0ljEDRg9oCT9YtGFxXFZP+t2xcEA/3U6IMgzAQ4IGgTCdXeCIejAFfzwZxUGLRjCSnOlfx6Jn7PPj2qo8eMBDAiqcsLTFflFbd7Yl67rSJGmcwH+xIJtW9IGbmfa2NvcHXqTjXQEwP4dw0qfKIStBYcLAr9fW0Bslh3oTZmjA9L9RnvScmVxALIjlFYY+7rUNbpAZKFIA4hoAn99Jtzu/HhQJEWUZkaksIn5LHEXecQ1uCofhPOubK5/7PecNuwHhB8ccYl2RV0WFB4JVhu6CBzFvM8ppFp26bRAS2NzaTRyevJuhO8lskh7FSt26LbHJOR1T4wU6Dmv87rs70buF4bZaTB2frssWcWjO94AD1AFrwAzmaR4WuFAUzxtMh1+/MexDbDa2EOMj+qgFaz8lcR7cW0MyTkrLOZcCTPe+inBnnTW2wnJ1nL/SxTjTgqBSceGBl04rU6CiNVTnp96MJDecMzsYLvvq7Qc5ZkANaLk68OJ/5VbTycnom7zGqPz49jnXWQ3TcZaVskv2Q19/LnQrE+9mEkoBeS24It+ZuHPqNAODH88WlKZR3ApkYF7GkaXVj8Wh3I6anTTObAb3jEuSUqBE8LSw9pAmS5ItGuEbvmBxkU0nnNwYmQo8inX5f8dXOtEKX0+n34OxmwURw4Bqxvfb4AQ8CUMkCnK/zfpEBwV9C6ixbqD/pnwF4DkrQQ7xnGi4o5+DNF9rDF2grbPLN2NsEdQV0M6NzHlwhfTLIQoyfgGNwmAyMw3X+LBmJfUTXuOtJyZj1RBgzxIxfJ0oIMPCiImGewMsdvkIwugBLdoDXeD9cLmjiEsMWAVlZv4T6RMNomr+AKt3xMJdhkhQv1hHvXk6bEZwjLvENOJ6uVuv1erX66ulgGNEYg+zyO/VEL9Hrr5z5IIB5vkvq1vObrrpfrb7gZPbyEV+eaIAPFPEpGJ7vXt3/Bw==) it looks very good.

**Comment by Simn** [comment]
Let's hope our markdown library handles it as well!

**Comment by markknol** [comment]
Cool. Please let me know when its on the website.

**Comment by Simn** [comment]
Will do, trying to figure out what's wrong with these links in the compiler defines.

**Comment by Simn** [comment]
No idea right now, they are fine in the markdown so it must go wrong somewhere later.

Anyway, it's published and looks good: http://haxe.org/manual/haxelib-using.html

**Comment by markknol** [comment]
Ah, the links are also fixed?

**Comment by Simn** [comment]
What the... so they are fixed. Magic?

**Comment by markknol** [comment]
maybe this \expr{<file.xml>} fixed it?

**Comment by Simn** [comment]
What footer links?

**Comment by markknol** [comment]
. it has a "next chapter " thing or am i crazy? its gone everywhere.

**Comment by ncannasse** [comment]
There's still a (red) broken link in "Using a Haxe library with the Haxe Compiler"

**Comment by markknol** [comment]
That part is not written yet as far as I can see. 

Or it should link to http://haxe.org/documentation/introduction/compiler-usage.html

**Comment by Simn** [comment]
That's because the page doesn't exist. I'm still not sure how to do this because we also have this information outside the manual at http://haxe.org/documentation/introduction/compiler-usage.html

**Comment by markknol** [comment]
May we could just use an url for this?

**Comment by Simn** [comment]
I don't want to duplicate it. But yes we could just link it.

**Comment by Simn** [comment]
Another option is to have all these lists in an appendix section in the manual and just link http://haxe.org/documentation/introduction/compiler-usage.html to them. That way we have all the content centralized.

**Comment by markknol** [comment]
I was more thinking of removing the current introduction section completely and add them all to the manual.

**Comment by Simn** [comment]
Yes we could do that. What I mean is that we can add the listings (metadata, compiler flags, compiler arguments, ...) at the end of the manual and link them so we don't have the entire feature set in the introduction section.

**Pull request merged**
