### PR TITLE
String encoding details

### PR DESCRIPTION
**Pull request by markknol**
Mostly copied from http://old.haxe.org/manual/encoding 

<del>:warning:  Cannot be merged yet, because I don't know how to write `\0`. </del>

Also not sure if this is still actual.

Closes https://github.com/HaxeFoundation/HaxeManual/issues/17

### CODE REVIEW

**Comment by jonasmalacofilho** [comment]
To write `\0` you should use `\textbackslash0`. More generally, you should `\textbackslash` or `\backslash` to type `\` in normal text or math mode.

**Comment by markknol** [comment]
Thanks, I now used `\textbackslash0`

**Comment by markknol** [comment]
Is this ok + correct now?

**Comment by Simn** [comment]
I don't know if that information is still accurate, have to check...

**Comment by Simn** [comment]
@frabbit: Could you check this as part of your Unicode adventures?

**Comment by markknol** [comment]
@frabbit can you check this?

**Comment by markknol** [comment]
@frabbit can you check this?

**Comment by Simn** [comment]
This is no longer accurate for Haxe 4, we'll have to update this...

**Pull request closed without merging**
