### PR TITLE
Debugging

### PR DESCRIPTION
**Pull request by markknol**
**Note: This is a work-in-progress-PR**

Goal: Provide info about debugging with Haxe. There is some info scattered in the manual and old wiki but I think it should be in one chapter.

The trace-section from language features is removed and split it the position/trace/$type into separate sections. I've added a JavaScript debugging section.

TODO:
- [ ] I think the hxcpp debugger info should be mentioned here too (https://github.com/HaxeFoundation/hxcpp-debugger/wiki/Getting-started) but I'm not sure how actual this is? Also, Im no cpp user, so I need help here.
- [ ] Do we have other secret debug functionality?
- [ ] Do we have other language specific debug information that is relevant to document?

### CODE REVIEW

**Comment by Simn** [comment]
Looks good to me. Did you try to actually TeX-compile this or are you still just hoping that it works?

**Comment by markknol** [comment]
I always hope it works. Haha, but I also tested it local ofcourse. So in current state it works.

**Comment by Simn** [comment]
Alright then, let me know when you want it merged.

**Comment by markknol** [comment]
When there is nothing more to add.
What do you know bout the hxcppdebugger?

**Comment by Simn** [comment]
Not much, but I wrote this once: https://github.com/HaxeFoundation/hxcpp-debugger/wiki/Getting-started

**Comment by markknol** [comment]
Yes that is exactly what I asked in first post :) how relevant is it? Because then ill port it, since wikis also seem to be hidden haha

**Comment by Simn** [comment]
We can have target-specific debugging sections I guess. Debugging is quite target-specific anyway.

**Comment by markknol** [comment]
Do you mean like i did now, or move it to the target-details section?

**Comment by Simn** [comment]
Like you did.

**Comment by markknol** [comment]
Lets go for this, ill add other sections later.

**Comment by markknol** [comment]
I've resolved the conflicts, should be mergable.

Reminder; when this is merged we need to add a redirect. (cc @ibilon)

**Pull request merged**
