### PR TITLE
removed underscore + no dots on of end description

### PR DESCRIPTION
**Pull request by markknol**

### CODE REVIEW

**Comment by Simn** [comment]
The dots should be fixed in the compiler...

**Comment by Simn** [comment]
Reminder to self: the `@:deprecated` description is deprecated.

**Comment by markknol** [comment]
The dots are already fixed in the compiler :wink:

**Comment by Simn** [comment]
Do are we planning to keep the changes in the compiler in sync with the manual?

**Comment by markknol** [comment]
I think half, since the description itself should be the same, but I now also have some links to other pages in the manual. (I think this cannot be automated)

**Pull request merged**
