### PR TITLE
Specifying version for dependencies (-lib name:ver).

### PR DESCRIPTION
**Pull request by fzzr-**
Add note about specifying version for dependencies.

### CODE REVIEW

**Comment by markknol** [comment]
Hey, thanks for your contribution. 

I noticed the CI-build is failed. Please change `[\ic{-lib library_name:version}]` to `\ic{-lib library_name:version}`  (leave the surrounding brackets). Then the build works and the pull-request can be merged. :+1:

**Comment by fzzr-** [comment]
Oh, sorry. I'll do it soon as possible.

**Comment by fzzr-** [comment]
It's been three months.

**Comment by Simn** [comment]
More like 12 minutes.

Anyway, I'll add this locally next time I work on the manual to avoid the commit mess.

**Comment by fzzr-** [comment]
I mean three months between Oct 7 and today.

**Pull request closed without merging**
