### PR TITLE
Interfaces can be extended

### PR DESCRIPTION
**Pull request by markknol**
Closes https://github.com/HaxeFoundation/HaxeManual/issues/165

### CODE REVIEW

**Comment by Simn** [comment]
Can you also add an example how to extend multiple interfaces? Also from -> by

**Comment by markknol** [comment]
Is that : extends A extends B
Didnt know that was possible?

**Comment by Simn** [comment]
See, that's why we document things. :)

We could also add a trivia that the syntax used to use `implements I` but was changed for Haxe 3. It's somewhat relevant for macro people because internally the extended interfaces are still stored in `cl_implements`, not `cl_extends`. But I can add that trivia later if you prefer.

**Comment by markknol** [comment]
Ha! And thats why I like contributing; to discover such unknown features. 

Please add this trivia, thats nice information :+1:

**Pull request merged**
