### PR TITLE
Fix outdated reference to -D analyzer

### PR DESCRIPTION
**Pull request by Gama11**
Also removed a stray backtick that seemed to break the markdown on the page:

### CODE REVIEW

**Comment by markknol** [comment]
@simn since which version does it work like this? Maybe we mention this change somewhere too?

**Comment by Gama11** [comment]
I think it's been that way since at least 3.3 / 3.4? So not sure if it's worth documenting the previous define for versions older than that at this point.

**Comment by markknol** [comment]
According this blogpost: https://haxe.org/blog/haxe-3.4-release/
> In Haxe 3.4 the static analyzer has settled and runs by default, so the -D analyzer flag has been removed. To have extra optimizations the -D analyzer-optimize can be used. This builds a control flow graph and then the optimizer (if enabled) does some optimizations on that, like folding expressions, removing dead code, etc. This optimization flag is not enabled by default because of too many vars being eliminated for hxcpp, in Haxe 4.0 it will be enabled by default. 

If that is the case, then the copy is not completely correct and first line should be:

```latex
The static analyzer is enabled by default and currently comes with the following modules.  To have extra optimizations \ic{-D analyzer-optimize} can be used. 
```
@Simn

**Comment by Aurel300** [comment]
Added in f5b02db.

**Pull request closed without merging**
