### PR TITLE
Add instantiation reification syntax

### PR DESCRIPTION
**Pull request by markknol**
I had [this question ](http://stackoverflow.com/questions/32179173/how-to-declare-instantiation-in-haxe-macro-function) about instantiation within a macro function. It seems to exist but it's not very documented well. I found the [Expression Reification page](http://haxe.org/manual/macro-reification-expression.html) only says `function $name() { }` from which you _could guess_ the syntax exist.

I'm not sure if we should also mention that a full path should be given here.

### CODE REVIEW

**Comment by Simn** [comment]
Does that really work? I thought `new` required a TypePath: http://api.haxe.org/haxe/macro/TypePath.html

**Comment by markknol** [comment]
Ah sorry yes that is true, maybe `instantiation \expr{new \$typePath() \{ \}}` is more clear then?

**Comment by Simn** [comment]
It's still in the wrong section because that listing deals with places where the internal structure expect strings.

**Comment by markknol** [comment]
Oh, I thought that list mentions the syntax since Haxe 3.1.0. 
What would be the correct place to put it?

**Comment by Simn** [comment]
A new paragraph I suppose.

**Pull request closed without merging**
