### PR TITLE
+ key HXCPP_GC_MOVING

### PR DESCRIPTION
**Pull request by fzzr-**
from https://github.com/HaxeFoundation/hxcpp/blob/c9e19a9c4ff700bde45797586cbf8ae251b4f35e/test/haxe/compile.hxml and some issues. [search-link](https://github.com/HaxeFoundation/hxcpp/search?utf8=✓&q=HXCPP_GC_MOVING)

### CODE REVIEW

**Comment by Simn** [comment]
I think this list was auto-generated somehow. I don't remember how exactly, but I think @jdonaldson was involved.

**Comment by fzzr-** [comment]
Wow. Auto-generated from/by what source? I think it's questionable, IMO :). Previously merged my additions: #183 #220 .

__Also__ we need a table look like Haxe compiler defines:

HxCpp Key | Description
------------ | -------------
HXCPP_GC_MOVING | Enable moving collector
HXCPP_SINGLE_THREADED_APP | Disable multithreading?

**Comment by underscorediscovery** [comment]
@fzzr- I can describe quite a lot of these, I was already documenting a lot of the hxcpp stuff as a wip, but I can surely elaborate on many of them. Feel free to ask me about ones you aren't sure.

Some of them I found out recently even, like `HXCPP_SINGLE_THREADED_APP` is :
> An optimization flag for when you know that you are not going to be creating any haxe threads. This allows hxcpp to assume a single thread and take a shorter path at times.

**Comment by Simn** [comment]
I'll merge this for now but we'll obviously have to check how to document these properly.

**Pull request merged**
