### PR TITLE
Invalid operators priority

### PR DESCRIPTION
**Pull request by RblSb**

### CODE REVIEW

**Comment by Simn** [comment]
I can't tell what this changes...

**Comment by markknol** [comment]
I think it just changes to order, to have it sorted on priority  (?)

**Comment by Simn** [comment]
Go for it

**Comment by RblSb** [comment]
It seems the travis error is irrelevant. Hope that the markup is correct.
Should fix HaxeFoundation/haxe#7070

**Comment by Simn** [comment]
You should run the converter to see if the markup looks good.

**Comment by RblSb** [comment]
@Simn have only same problem as current file version :)
https://gist.github.com/RblSb/f27361af31103de924cb853783b12c00
https://github.com/HaxeFoundation/HaxeManual/blob/master/output/HaxeManual/website/types-numeric-operators.md

**Comment by Simn** [comment]
Yeah I still don't know why that happens...

**Pull request merged**
