### PR TITLE
Updated "Using external JavaScript libraries"

### PR DESCRIPTION
**Pull request by andyli**
Updated "Using external JavaScript libraries" to include info on the new jQuery/swfobject externs.

### CODE REVIEW

**Comment by markknol** [comment]
Looks good to me! 

Offtopic question; what does `@:selfCall` do?

**Comment by andyli** [comment]
It denotes that function is a direct call to the object. In case of applying `@:selfCall` to the constructor, it avoids generating `new`. e.g. `new JQuery("div")` will be outputted as `$("div")` instead of `new $("div")`. Maybe I should add that info to the manual too.

**Comment by nadako** [comment]
@markknol see https://github.com/HaxeFoundation/haxe/issues/3441

**Comment by markknol** [comment]
Nice! Would be good idea to document. Is this JS specific?

**Comment by andyli** [comment]
Just added some doc on `@:selfCall`. Yes, the current implementation of it is JS specific.

**Comment by Simn** [comment]
Did you check if the markdown converter handles the table correctly? That was a bit finicky so I might have to adjust some things.

**Comment by andyli** [comment]
I've just checked the output and fixed a few things.
The markdown output is fine now, but the ebook ones do not. The [table in introduction](https://github.com/HaxeFoundation/HaxeManual/blob/master/HaxeManual/01-introduction.tex#L16-L30) is not correctly handled in the .epub either. Is that expected?

**Comment by Simn** [comment]
I couldn't figure out what's causing that yet. IIRC some tables were working and other were not. It's not very important though, so if the markdown output works I'm fine with merging this. Thanks!

**Pull request merged**
