### PR TITLE
Update 06-language-features.tex

### PR DESCRIPTION
**Pull request by markknol**
Create maps with array comprehension

### CODE REVIEW

**Comment by Gama11** [comment]
"Using array comprehension to create maps" sounds quite strange to me. Shouldn't that be called _map_ comprehension in that case?

**Comment by Simn** [comment]
Yeah this is not really a good place for it.

**Comment by markknol** [comment]
Is this any good? Otherwise lets close it.

**Comment by Simn** [comment]
The content is fine but it's strange to have this under array comprehension.

**Comment by ibilon** [comment]
How about making a page "Map comprehension".

**Comment by Simn** [comment]
I'll go ahead and close this because it no longer merges.

**Comment by markknol** [comment]
Good, because we already have it here too: https://haxe.org/manual/lf-map-comprehension.html

**Pull request closed without merging**
