### PR TITLE
introduction language features

### PR DESCRIPTION
**Pull request by markknol**
Copied from http://haxe.org/documentation/introduction/language-features.html

### CODE REVIEW

**Comment by Simn** [comment]
Mmh, I don't really like having duplicates like that...

**Comment by markknol** [comment]
Ah I thought the plan was to remove pages from the "introduction" and let them all be part in the manual. Just like the "Compiler Usage"

**Comment by Simn** [comment]
Ah, yeah, I suppose it doesn't matter if we just change the link.

**Comment by markknol** [comment]
Any ideas how we do that?

**Pull request merged**
