### PR TITLE
add some lua-specific feature details

### PR DESCRIPTION
**Pull request by jdonaldson**
Here's some notes on the Lua target.  Does this look right?  I couldn't work out how to build the website.

### CODE REVIEW

**Comment by Gama11** [comment]
Some minor things I've noticed:

- capitalization is a bit inconsistent, sometimes you use `haxe`/`lua`, sometimes `Haxe`/`Lua` (the latter is correct I think)
- the proper spelling for `Luarocks` seems to be `LuaRocks` according to their site

**Comment by jdonaldson** [comment]
Mark thanks for updating, this has fallen off my radar.  I will add some more tips and tricks soon.

**Comment by markknol** [comment]
Ok it now passes Travis, is this mergable as is?

**Comment by markknol** [comment]
Thanks! 

Love to see those tips and tricks!

**Pull request merged**
