### PR TITLE
@:functionCode and @:functionTailCode descripton

### PR DESCRIPTION
**Pull request by dkolyesnik**
Added @:functionCode and @:functionTailCode description

### CODE REVIEW

**Comment by nadako** [comment]
Isn't that list autogenerated from the compiler description? @markknol ?

**Comment by profelis** [comment]
```
$ haxe --help-metas | grep "@:function"                                                       
 @:functionCode         : Used to inject platform-native code into a function
 @:functionTailCode     :  (cpp only)
```
@nadako

**Comment by markknol** [comment]
No I copy/pasted it once from there but added some markup/links to it. So this is a good addition. 

We might want to double check if the rest is still up to date.

**Comment by markknol** [comment]
Thanks!

If any other metadata needs to be updated, please open a new PR.

**Pull request merged**
