### PR TITLE
Added Inference status section

### PR DESCRIPTION
**Pull request by markknol**
I gathered some information from several issue pages, please double check.

Closes https://github.com/HaxeFoundation/HaxeManual/issues/54

### CODE REVIEW

**Comment by Simn** [comment]
I'm still not sure if this behavior should be surfaced to the user. It's pretty much an implementation detail with some consequences.

**Comment by markknol** [comment]
Are you saying that In that case it shouldnt be catergorized in statusses like this?

**Comment by Simn** [comment]
Const status has been removed so we have to update this.

**Comment by markknol** [comment]
Can you take care of it? 
Also because you weren't sure if his was relevant enough to communicate.

**Comment by Simn** [comment]
Okay, let's not document this for now, I really think it's an implementation detail.

**Comment by Simn** [comment]
Keep the branch though.

**Pull request closed without merging**
