### PR TITLE
Update meta and defines list to Haxe 3.2.0

### PR DESCRIPTION
**Pull request by Gama11**
I was mostly going through the list comparing --help-metas and --help-defines with these, looking for added / removed entires and ones that changed order. That means I could easily have missed some changed descriptions.

### CODE REVIEW

**Comment by Gama11** [comment]
@Simn Any changes required here?

**Comment by markknol** [comment]
Could you also apply the new defines to the target detail pages?

**Comment by Simn** [comment]
Is this just taken from common.ml?

**Comment by Gama11** [comment]
@markknol Sure, didn't know that was a thing.

@Simn from the command-line - so pretty much yes, except for the Internal metadata which doesn't show in --help-metas.

**Comment by Simn** [comment]
We should have some tool to generate this list from the command line output...

**Comment by Gama11** [comment]
I thought the same while doing this, it's very tedious and error-prone to update this manually.

However, it's somewhat tricky because there are random links / formatting in there, like `\{tref}` and `\expr{expr}`.

**Comment by markknol** [comment]
In this table, http://haxe.org/manual/cr-metadata.html there are extra references to other pages.

**Pull request merged**
