### PR TITLE
document variable shadowing

### PR DESCRIPTION
**Pull request by nadako**

### CODE REVIEW

**Comment by Simn** [comment]
Looks good. I wonder if we should mention this case while we're at it:

```haxe
var a = 1;
function f() {
    trace(a);
}
var a = 2;
f(); // traces 1
```

This makes it clear that the shadowing strictly follows syntax and that you don't have to worry about re-declaring a variable that is captured by a closure.

**Comment by nadako** [comment]
That's a nice example! Do you want me to add it or are you going to do it?

**Comment by nadako** [comment]
BTW, maybe it should have a separate sub-heading so we can link to these explanations.

**Comment by Simn** [comment]
Feel free to add it to this PR.

And I agree, we should have more paragraphs. You can just add `\paragraph{Variable Shadowing}` for that.

**Comment by nadako** [comment]
ok, done

**Comment by nadako** [comment]
thanks! publish soon?

**Comment by Simn** [comment]
Uhm, I thought this published automatically...

**Comment by ibilon** [comment]
Not anymore, the haxelib repository needs to update the haxemanual submodule (which will trigger travis).
I'll do that right now.

**Comment by nadako** [comment]
That's nice, actually, thanks!

**Pull request merged**
