### PR TITLE
Update 06-language-features.tex

### PR DESCRIPTION
**Pull request by markknol**
Missing code blocks, added link to conditional compilation page.

### CODE REVIEW

**Comment by Simn** [comment]
I think at some point I wanted to use `\expr{}` only for actual Haxe expressions so we could add some syntax highlighting later. There was some other command to use for general monospace. I didn't really go through with that though, so I'm fine with merging. Thanks!

**Comment by markknol** [comment]
Ok good to know, so what should i use for non-code things? Like commandline/filename expressions and stuff?

**Comment by Simn** [comment]
I forget... :D

**Comment by markknol** [comment]
I think it is `/ic{}` ?

**Comment by Simn** [comment]
That might be it! Though I have no idea what that stands for.

**Pull request merged**
